Fix build error in test container for `rfdc` usage.
Usage was added a month ago in src/index.ts but worked via npm's "secondary package" visibility. Apparently, that visibility goes away when linking packages.

This package, rfdc, was approved earlier and is also already in our secondary dependencies.

Error was:
src/index.ts:136:23 - error TS2307: Cannot find module 'rfdc' or its corresponding type declarations.